{{- if and .Values.ingress.enabled (not .Values.global.suspend) }}
{{- $fullName := include "library-chart.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "library-chart.ingress.annotations" . | nindent 4 }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.security.allowlist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.security.allowlist.ip | quote }}
    {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      {{- if .Values.ingress.useCertManager }}
      secretName: tls-cert-{{ $fullName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ required "ingress.hostname est obligatoire quand ingress.enabled." .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.networking.service.port }}
{{- end }}
